version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/tower-oauth2-resource-server"
      - "/examples/axum-example"
      - "/examples/salvo-example"
      - "/examples/tonic-example"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5