[package]
name = "tower-oauth2-resource-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
jsonwebtoken = { workspace = true}
log = { workspace = true }
pin-project = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
ureq = { workspace = true }

[dev-dependencies]
base64 = { workspace = true }
http-body-util = { workspace = true }
bytes = { workspace = true }
lazy_static = { workspace = true }
mockall = { workspace = true }
rand = { workspace = true }
rsa = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
wiremock = { workspace = true }
