[package]
name = "tower-oauth2-resource-server"
description = "Tower middleware that provides JWT authorization against an OpenID Connect (OIDC) Provider"
keywords = ["jwt", "oidc", "oauth2", "authorizer"]
license = "MIT"
homepage = "https://github.com/Dunklas/tower-oauth2-resource-server"
repository = "https://github.com/Dunklas/tower-oauth2-resource-server"
readme = "README.md"
version = "0.1.4"
edition = "2021"
exclude = ["tests"]

[dependencies]
async-trait = "0.1.83"
futures-util = "0.3.30"
http = "1.1.0"
jsonwebtoken = "9.3.0"
log = { workspace = true }
mockall_double = "0.3.1"
pin-project = "1.1.7"
reqwest = { version = "0.12.9", default-features = false, features = ["json"] }
serde = "1.0.215"
serde_with = "3.9.0"
tokio = { workspace = true, features = ["rt", "sync", "time"] }
tower = { workspace = true }
url = { version = "2.5.4", features = ["serde"] }

[dev-dependencies]
base64 = "0.22.1"
http-body-util = "0.1.2"
bytes = "1.9.0"
lazy_static = "1.4.0"
mockall = "0.13.1"
rand = "0.8.5"
rsa = "0.9.7"
serde_json = "1.0.133"
tower = { workspace = true, features = ["util"] }
tokio = { workspace = true, features = ["rt-multi-thread"]}
wiremock = "0.6.0"

[features]
default = ["default-tls"]
default-tls = ["reqwest/default-tls"]
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]
