[package]
name = "tower-oauth2-resource-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
futures-util = "0.3.30"
http = { workspace = true }
jsonwebtoken = "9.3.0"
log = { workspace = true }
pin-project = "1.1.5"
reqwest = { version = "0.12.8", default-features = false, features = ["json"] }
serde = "1.0.210"
serde_with = "3.9.0"
tokio = { workspace = true, features = ["rt", "sync", "time"] }
tower = { workspace = true }

[dev-dependencies]
base64 = "0.22.1"
http-body-util = "0.1.2"
bytes = "1.6.0"
lazy_static = "1.4.0"
mockall = "0.12.1"
rand = "0.8.5"
rsa = "0.9.6"
serde_json = "1.0.117"
tower = { workspace = true, features = ["util"] }
wiremock = "0.6.0"

[features]
default = ["default-tls"]
default-tls = ["reqwest/default-tls"]
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]
